### ISSUE TITLE
Let's improve the exercise

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m2-evaluacion-intermedia-asoto89#1]
Really cool job @asoto89  !!!

Here you have some tips to improve the exercise:

- [x] Remember to convert input value string to a number
- [x] Extract the feedback painter to a function
- [x] Fix the if's structure now you are working with numbers:
- [x] Move the feedback logic to a function an execute it on each click
- [x] Move your counter logic into a function and execute it on each click
- [x] You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting the enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by alejandrasotoa** [comment]
Hi Carlos! I made the changes you suggested and added a couple of thing extra, including a hot/cold animation to tell the user is close to the answer. 
Thanks for the help :) !

**Comment by oneeyedman** [comment]
Hi, @asoto89! 

This is a super cool exercise!! Super well done.

I notice that the counter is not working correctly, is it possible that the counter variable goes back to zero every time the user pushes the play button?

Here you have a mistery gif:
![Mistery](https://media.giphy.com/media/6l5PF70VKQCw8/giphy-downsized.gif)

**Comment by alejandrasotoa** [comment]
Ups! I forgot to remove it from the startGame function. Now it fixed! also I changed the feedback position for make it easier to see on mobile. Thanks for the feedback!!!! :smile:

**Comment by oneeyedman** [comment]
Excellent job, @asoto!!!
